on: pull_request
name: Check and lint
jobs:
  review_codestyle:
    name: Codestyle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.4
        coverage: none
    - name: Install Reviewdog
      run: |
        wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $PWD/ latest
    - name: Install Dependencies
      run: |
        composer install --no-interaction --no-progress
    - name: Check codestyle
      run: |
        vendor/bin/phpcs --report=checkstyle | ./reviewdog -f=checkstyle -name=PHPCS -reporter=github-pr-check
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  static_code_analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.4
        coverage: none
    - name: Install Reviewdog
      run: |
        wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $PWD/ latest
    - name: Install Dependencies
      run: |
        composer install --no-interaction --no-progress
    - name: Static code analysis
      run: |
        php -d memory_limit=1G vendor/bin/phpstan analyse . --error-format=checkstyle | ./reviewdog -f=checkstyle -name=PHPStan -reporter=github-pr-check
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  markdown_lint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Lint README.md file
      uses: docker://avtodev/markdown-lint:v1
      with:
        args: './README.md'

  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: brpaz/hadolint-action@v1.4.0
